### ISSUE TITLE
gsl.pc and gsl/gsl_rng.h files not found

### ISSUE THREAD

**Issue by ThibauldMichel** [microsoft/GSL#1111]
Hello, I try to install gsl as a dependency of ngsF. 
I work with conda 4.12.0 in a dedicated environment.
The installation of ngsF warned that the gsl.pc and gsl/gsl_rng.h files are not found:

```
cd ngsF
make
make -C htslib bgzip
make[1]: Entering directory '/mnt/shared/scratch/usr/folder/scripts/ngsF/htslib'
make[1]: 'bgzip' is up to date.
make[1]: Leaving directory '/mnt/shared/scratch/usr/folder/scripts/ngsF/htslib'
Package gsl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gsl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gsl' found
g++ -I -I /usr/share/ghostscript/lib/gslp.ps  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE  -c read_data.cpp
read_data.cpp:1:10: fatal error: gsl/gsl_rng.h: No such file or directory
 #include <gsl/gsl_rng.h>
```

Therefore I have re-installed gsl with conda, and the installed version is 2.28.
`conda install -c conda-forge gsl`
However, when trying to find the gsl files I need, they are not showing up:
```

which gsl
/usr/bin/which: no gsl in (/mnt/shared/scratch/usr/apps/conda/envs/angsd/bin:/home/usr/.local/bin:/home/usr/.local/bin:/home/usr/bin:/opt/openmpi/latest/bin:/opt/slurm/latest/bin:/usr/share/Modules/bin:/mnt/shared/apps/guppy/4.2.2:/mnt/shared/apps/aspera/3.9.2/bin:/mnt/cluster/scripts:/mnt/shared/scratch/usr/apps/conda/condabin:/mnt/shared/scratch/usr/apps/conda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)

locate gsl
/opt/rh/gcc-toolset-9/root/usr/include/c++/9/bits/gslice.h
/opt/rh/gcc-toolset-9/root/usr/include/c++/9/bits/gslice_array.h
/usr/include/c++/8/bits/gslice.h
/usr/include/c++/8/bits/gslice_array.h
/usr/share/ghostscript/lib/gslp.ps

```
Have you seen this issue before?

**Comment by dmitrykobets-msft** [comment]
Hi @ThibauldMichel, this repo is a lightweight safety library for C++. Based on the error output, are you instead looking for https://www.gnu.org/software/gsl/?

**Comment by ThibauldMichel** [comment]
Thank you @dmitrykobets-msft, I will re-post my question to them!
