### ISSUE TITLE
Installation giudelines of GSL in ubuntu 16.04

### ISSUE THREAD

**Issue by jack17529** [Microsoft/GSL#524]
As mentioned that it works on GNU/Linux using GCC 5.1
Can someone please help me in installing it in Ubuntu as I got stuck here -
"These steps assume the source code of this repository has been cloned into a directory named c:\GSL."

Thank You

**Comment by galik** [comment]
Assuming you want to store your development libraries in $HOME/dev you should be able to do the following at the command line.
```bash
# go to HOME folder
cd

# ensure you have the development folder
mkdir -f dev

# go there
cd dev

# get the GSL library
git clone https://github.com/Microsoft/GSL.git

# go there
cd GSL

# create a folder to build the test files in
mkdir build

# go there
cd build

# get cmake to generate your Makefile
cmake $HOME/dev/GSL

# build the test programs
cmake --build . --config Debug

# run the test programs
ctest -C Debug
```
Hope that helps. It's the instructions copied from the front page assuming `$HOME/dev/GSL` rather than `C:\GSL`

**Comment by jack17529** [comment]
@galik  that worked, but how to use it is another problem for me -
`#include<iostream>
#include <gsl.h>
//#include<boost/optional.hpp>
using namespace std;

int main(){
	int x = 5;
	gsl::owner<int*>p = &x;

//	boost::optional<int>;

	return 0;
}`
and tried to compile it like -
'jack@jack-Latitude-3460:~/Desktop/C++ Advanced/TPayne$ g++ -I/home/dev/GSL boost_gsl.cpp 
boost_gsl.cpp:2:17: fatal error: gsl.h: No such file or directory
compilation terminated.'

and got error, am I doing it right.

Thanks!

**Comment by galik** [comment]
If you look right down at the bottom of the README.md here: https://github.com/Microsoft/GSL/blob/master/README.md

GCC/clang

    -I$HOME/dev/GSL/include

Include the library using:

    #include <gsl/gsl>

Note: `$HOME` is **not** the same as `/home` so `/home/dev` is the wrong path. You need `$HOME/dev`.

So try compiling using *this* command:
```bash
g++ -std=c++14 -Wall -Wextra -pedantic-errors -I$HOME/dev/GSL/include -o progname progname.cpp
```

And when you *include* GSL in your program use this:
```cpp
#include <gsl/gsl>
```

You can't use `#include <gsl.h>` that won't work.

**Comment by neilmacintosh** [comment]
Looks like this has been resolved with some extra details from @galik!
